name: build debug

on:
  pull_request:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    outputs:
      apk_path: ${{ steps.build.outputs.apk_path }}
      bundle_path: ${{ steps.build.outputs.bundle_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get short Git hash
        id: version
        run: |
          SHORT_GIT_SHA=$(git rev-parse --short HEAD)
          echo "version_name=ci-${SHORT_GIT_SHA}" >> $GITHUB_OUTPUT

      - name: Build Android
        id: build
        uses: ./.github/actions/build-android
        with:
          version_name: ${{ steps.version.outputs.version_name }}
          build_type: debug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts-${{ steps.version.outputs.version_name }}
          path: |
            ${{ steps.build.outputs.apk_path }}
            ${{ steps.build.outputs.bundle_path }}
          retention-days: 3
